### ISSUE TITLE
Start-api fails with Exit status 1

### ISSUE THREAD

**Issue by tennysonp** [cezerin/cezerin#403]
Mac Osx: Sierra 10.12.16
mongo: v3.6.3
node: v6.11.2

When running "npm start " get this error.

![screen shot 2018-03-15 at 5 55 04 pm](https://user-images.githubusercontent.com/1958230/37493131-40d96922-287a-11e8-8a71-baa6d6838467.png)

This is whats in the debug log

1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/Users/username/.node/bin/npm',
1 verbose cli   'run',
1 verbose cli   'start-api' ]
2 info using npm@5.0.4
3 info using node@v6.11.2
4 verbose run-script [ 'prestart-api', 'start-api', 'poststart-api' ]
5 info lifecycle cezerin@0.33.0~prestart-api: cezerin@0.33.0
6 silly lifecycle cezerin@0.33.0~prestart-api: no script for prestart-api, continuing
7 info lifecycle cezerin@0.33.0~start-api: cezerin@0.33.0
8 verbose lifecycle cezerin@0.33.0~start-api: unsafe-perm in lifecycle true
9 verbose lifecycle cezerin@0.33.0~start-api: PATH: /Users/username/.node/lib/node_modules/npm/bin/node-gyp-bin:/Users/username/Sites/ecommerce/cezerin/node_modules/.bin:/Users/username/Downloads/google-cloud-sdk/bin:/usr/local/heroku/bin:/Users/username/.node/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/git/bin:/usr/local/MacGPG2/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/usr/local/bin:/Users/username/Library/Android/sdk/platform-tools:/Users/username/Library/Android/sdk/tools:/Users/username/Developer/ant/apache-ant-1.9.4.3/bin
10 verbose lifecycle cezerin@0.33.0~start-api: CWD: /Users/username/Sites/ecommerce/cezerin
11 silly lifecycle cezerin@0.33.0~start-api: Args: [ '-c', 'node src/api/server/index.js' ]
12 silly lifecycle cezerin@0.33.0~start-api: Returned: code: 1  signal: null
13 info lifecycle cezerin@0.33.0~start-api: Failed to exec start-api script
14 verbose stack Error: cezerin@0.33.0 start-api: `node src/api/server/index.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/Users/username/.node/lib/node_modules/npm/lib/utils/lifecycle.js:283:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/Users/username/.node/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:891:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid cezerin@0.33.0
16 verbose cwd /Users/username/Sites/ecommerce/cezerin
17 verbose Darwin 16.7.0
18 verbose argv "/usr/local/bin/node" "/Users/username/.node/bin/npm" "run" "start-api"
19 verbose node v6.11.2
20 verbose npm  v5.0.4
21 error code ELIFECYCLE
22 error errno 1
23 error cezerin@0.33.0 start-api: `node src/api/server/index.js`
23 error Exit status 1
24 error Failed at the cezerin@0.33.0 start-api script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]

Any help will be appriciated!

**Comment by tennysonp** [comment]
So sorry guys - I upgraded to Node version 8.10.0 and it started working. Now I am getting another error:  
--- error: API error MongoError: exception: Unrecognized pipeline stage name: '$lookup'

**Comment by restmount** [comment]
Hi @tennysonp 
do you initialize MongoDB with default data?
https://github.com/cezerin/cezerin/blob/master/docs/initialize-mongodb.md

**Comment by tennysonp** [comment]
Thanks @restmount that was it.

**Comment by kerven66** [comment]
The same as tennysonp happens to me when running "npm start" for the first time: "Start-api fails with Exit status 1". Upgrading node is not solution for me, because I'm working with 9.8.0 version.

This is the content of debug.log:
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@5.6.0
3 info using node@v9.8.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle cezerin@0.33.0~prestart: cezerin@0.33.0
6 info lifecycle cezerin@0.33.0~start: cezerin@0.33.0
7 verbose lifecycle cezerin@0.33.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle cezerin@0.33.0~start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/var/www/vhosts/ees.es/httpdocs/cezerin/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
9 verbose lifecycle cezerin@0.33.0~start: CWD: /var/www/vhosts/ees.es/httpdocs/cezerin
10 silly lifecycle cezerin@0.33.0~start: Args: [ '-c',
10 silly lifecycle   'NODE_ENV=production npm run start-api & npm run start-store' ]
11 silly lifecycle cezerin@0.33.0~start: Returned: code: 1  signal: null
12 info lifecycle cezerin@0.33.0~start: Failed to exec start script
13 verbose stack Error: cezerin@0.33.0 start: `NODE_ENV=production npm run start-api & npm run start-store`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at EventEmitter.emit (events.js:180:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:180:13)
13 verbose stack     at maybeClose (internal/child_process.js:936:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
14 verbose pkgid cezerin@0.33.0
15 verbose cwd /var/www/vhosts/ees.es/httpdocs/cezerin
16 verbose Linux 3.10.0-693.17.1.el7.x86_64
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
18 verbose node v9.8.0
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error cezerin@0.33.0 start: `NODE_ENV=production npm run start-api & npm run start-store`
22 error Exit status 1
23 error Failed at the cezerin@0.33.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by amey10794** [comment]
Ubuntu 16.04
node v8.9.3
mongo 5.5.1
Hey @restmount I am facing the same error. I have initialized Mongodb with the default collections but I deleted the default documents inside the collections and added custom documents. From my observation, I usually get this error when I try to access the Mongodb database using Express. 
I appreciate your help.Thanks
